arb-dir: lib/core/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/l10n
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
preferred-supported-locales: [ en, es ]
